paths-ignore:
  - "**/vendor/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  - "**/tests/**"
  - "**/uploads/**"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/package-lock.json"
  - "**/yarn.lock"
  - "**/composer.lock"
  - "**/.git/**"
  - "**/.github/**"
  - "**/.vscode/**"
  - "**/__pycache__/**"
  - "**/*.log"
  - "**/*.sql"
  - "**/event_log.txt"
  - "**/config/**"

matches-ignore:
  - name: "Test Data"
    match: "test.*|mock.*|example.*|sample.*"
  - name: "Log Files"
    match: ".*\.log$"
  - name: "SQL Files"
    match: ".*\.sql$" 