name: Deploy to GitHub Pages

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp -r view deploy/
          cp index.php deploy/
          cp .htaccess deploy/
          cp .nojekyll deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          force_orphan: true
          allow_empty_commit: false
          keep_files: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: |
            .github
            vendor
            config
            controller
            tests
            uploads
            indexation
            *.sql
            *.log
            composer.*
